Repository techInterview-study/testttRepo, pull requests merged in 2024-01, with the labels that each got.

#2 feat : 오 성 환 commit
  network/img/dd.jpg
  network/오성환.md
Labels: bug, documentation, duplicate, enhancement, good first issue

#3 feat : 이치왕 commit
  network/이치왕.md
Labels: documentation

#4 feat : 이효림 commit
  network/img/Capture001.png
  network/이효림.md
Labels: documentation

#6 feat : 이 윤 하 commit
  network/img/images.jpeg
  network/이윤하.md
Labels: help wanted

#7 feat : 이 재 성 commit
  network/img/duck.jpeg
  network/이재성.md
Labels: good first issue

#9 size 변경
  network/송예진.md
Labels: enhancement

#10 docs : stack and queue 내용 정리
  .idea/.gitignore
  .idea/misc.xml
  .idea/modules.xml
  .idea/testttRepo.iml
  .idea/vcs.xml
  network/data_structure_stack_and_queue.md
  network/img/LIFO.png
  network/img/memory_area.webp
Labels: documentation
